consolidate the steps

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -45,27 +45,23 @@ jobs:
     steps:
     - uses: actions/checkout@v2
     - name: Build and run unit tests
-      run: xcodebuild clean test -scheme whatdid-debug
-  todos:
-    runs-on: macos-latest
-    steps:
-    - uses: actions/checkout@v2
+      run: xcodebuild clean test -scheme whatdid-debug | tee build.stdout
     - name: Look for TODOs
       run: |
+            # Check for TODOs
             # Each line will be something like:
             # /path/to/whatdid/whatdid/main/SomeFile.swift:1234:56: warning: todo hello
             #
             # The output format for GH actions is:
             # ::error file={name},line={line},endLine={endLine},title={title}::{message}
             set -euo pipefail
-            exit_code=0
-            xcodebuild clean build -scheme whatdid-debug 2>/dev/null |
-              grep -i 'warning: todo' |
-              sort -u |
-              while read -r line; do
-                IFS=: read filename fileline filecol warning message <<< "$line"
-                message="$(echo "$message" | sed 's/ *todo  *//')"
-                printf '::error file=%s,line=%s,col=%s,title=Found TODO::%s\n' "$filename" "$fileline" "$filecol" "$message"
-                exit_code=1
-              done
-              exit "$exit_code"
+            grep -i 'warning: todo' build.stdout | sort -u > todos.txt
+            while read -r line; do
+              IFS=: read filename fileline filecol warning message <<< "$line"
+              message="$(echo "$message" | sed 's/ *todo  *//')"
+              printf '::error file=%s,line=%s,col=%s,title=Found TODO::%s\n' "$filename" "$fileline" "$filecol" "$message"
+            done < todos.txt
+            if [[ -s todos.txt ]]; then
+              exit 1
+            fi
+            
